AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  newsroom-scraper

Globals:
  Function:
    Timeout: 3

Resources:
  NewsroomFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        Newsroom:
          Type: Api
          Properties:
            Path: /newsroom
            Method: get
